---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "csi-driver-node.extensionsGroup" . }}:{{ include "csi-driver-node.name" . }}:csi-driver-controller-disk
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["list"]
