replicas: 1
podAnnotations: {}
images:
  remedy-controller-azure: image-repository:image-tag
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

manager:
  metricsPort: 6000
targetManager:
  metricsPort: 6001

controllers:
  publicipaddress:
    concurrentSyncs: 5
  virtualmachine:
    concurrentSyncs: 5
  service:
    concurrentSyncs: 5
  node:
    concurrentSyncs: 5

disableControllers: []
targetDisableControllers: []

config:
  clientConnection:
    acceptContentTypes: application/json
    contentType: application/json
    qps: 100
    burst: 130
  azure:
    orphanedPublicIPRemedy:
      requeueInterval: 1m
      deletionGracePeriod: 5m
      maxGetAttempts: 5
      maxCleanAttempts: 5
    failedVMRemedy:
      requeueInterval: 1m
      maxGetAttempts: 5
      maxReapplyAttempts: 5
