images:
- name: terraformer
  sourceRepository: github.com/gardener/terraformer
  repository: eu.gcr.io/gardener-project/gardener/terraformer-azure
  tag: "v2.4.0"

- name: cloud-controller-manager
  sourceRepository: github.com/kubernetes/kubernetes
  repository: k8s.gcr.io/hyperkube
  targetVersion: "< 1.17"
- name: cloud-controller-manager
  sourceRepository: github.com/gardener/cloud-provider-azure
  repository: eu.gcr.io/gardener-project/kubernetes/cloud-provider-azure
  tag: "v1.17.17"
  targetVersion: "1.17.x"
- name: cloud-controller-manager
  sourceRepository: github.com/gardener/cloud-provider-azure
  repository: eu.gcr.io/gardener-project/kubernetes/cloud-provider-azure
  tag: "v1.18.17"
  targetVersion: "1.18.x"
- name: cloud-controller-manager
  sourceRepository: github.com/gardener/cloud-provider-azure
  repository: eu.gcr.io/gardener-project/kubernetes/cloud-provider-azure
  tag: "v1.19.9"
  targetVersion: "1.19.x"
- name: cloud-controller-manager
  sourceRepository: github.com/gardener/cloud-provider-azure
  repository: eu.gcr.io/gardener-project/kubernetes/cloud-provider-azure
  tag: "v1.20.5"
  targetVersion: ">= 1.20"
- name: machine-controller-manager
  sourceRepository: github.com/gardener/machine-controller-manager
  repository: eu.gcr.io/gardener-project/gardener/machine-controller-manager
  tag: "v0.38.0"

- name: csi-driver-disk
  sourceRepository: github.com/kubernetes-sigs/azuredisk-csi-driver
  repository: mcr.microsoft.com/k8s/csi/azuredisk-csi
  tag: "v0.9.0"
- name: csi-driver-file
  sourceRepository: github.com/kubernetes-sigs/azurefile-csi-driver
  repository: mcr.microsoft.com/k8s/csi/azurefile-csi
  tag: "v0.8.0"
- name: csi-provisioner
  sourceRepository: github.com/kubernetes-csi/external-provisioner
  repository: k8s.gcr.io/sig-storage/csi-provisioner
  tag: "v1.6.0"
- name: csi-attacher
  sourceRepository: github.com/kubernetes-csi/external-attacher
  repository: k8s.gcr.io/sig-storage/csi-attacher
  tag: "v2.2.0"
- name: csi-snapshotter
  sourceRepository: github.com/kubernetes-csi/external-snapshotter
  repository: k8s.gcr.io/sig-storage/csi-snapshotter
  tag: "v2.1.5"
- name: csi-snapshot-controller
  sourceRepository: github.com/kubernetes-csi/external-snapshotter
  repository: k8s.gcr.io/sig-storage/snapshot-controller
  tag: "v2.1.5"
- name: csi-resizer
  sourceRepository: github.com/kubernetes-csi/external-resizer
  repository: k8s.gcr.io/sig-storage/csi-resizer
  tag: "v0.5.0"
- name: csi-node-driver-registrar
  sourceRepository: github.com/kubernetes-csi/node-driver-registrar
  repository: k8s.gcr.io/sig-storage/csi-node-driver-registrar
  tag: "v1.3.0"
- name: csi-liveness-probe
  sourceRepository: github.com/kubernetes-csi/livenessprobe
  repository: k8s.gcr.io/sig-storage/livenessprobe
  tag: "v2.2.0"

- name: remedy-controller-azure
  sourceRepository: github.com/gardener/remedy-controller
  repository: eu.gcr.io/gardener-project/gardener/remedy-controller/remedy-controller-azure
  tag: "v0.7.0"
