images:
- name: terraformer
  sourceRepository: github.com/gardener/terraformer
  repository: eu.gcr.io/gardener-project/gardener/terraformer
  tag: "v1.0.0"
- name: cloud-controller-manager
  sourceRepository: github.com/kubernetes/kubernetes
  repository: k8s.gcr.io/hyperkube
  targetVersion: "< 1.17"
- name: cloud-controller-manager
  sourceRepository: github.com/gardener/cloud-provider-azure
  repository: eu.gcr.io/gardener-project/kubernetes/cloud-provider-azure
  tag: "v1.17.4"
  targetVersion: "1.17.x"
- name: cloud-controller-manager
  sourceRepository: github.com/gardener/cloud-provider-azure
  repository: eu.gcr.io/gardener-project/kubernetes/cloud-provider-azure
  tag: "v1.18.0"
  targetVersion: ">= 1.18"
- name: machine-controller-manager
  sourceRepository: github.com/gardener/machine-controller-manager
  repository: eu.gcr.io/gardener-project/gardener/machine-controller-manager
  tag: "v0.29.0"
