apiVersion: v1
kind: Service
metadata:
  name: remedy-controller-azure
  namespace: {{ .Release.Namespace }}
  labels:
    app: remedy-controller-azure
  annotations:
    networking.resources.gardener.cloud/from-all-scrape-targets-allowed-ports: '[{"port":{{ .Values.manager.metricsPort }},"protocol":"TCP"}]'
    # TODO: This label approach is deprecated and no longer needed in the future. Remove them as soon as gardener/gardener@v1.75 has been released.
    networking.resources.gardener.cloud/from-policy-pod-label-selector: all-scrape-targets
    networking.resources.gardener.cloud/from-policy-allowed-ports: '[{"port":{{ .Values.manager.metricsPort }},"protocol":"TCP"}]'
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    port: {{ .Values.manager.metricsPort }}
    protocol: TCP
  - name: target-metrics
    port: {{ .Values.targetManager.metricsPort }}
    protocol: TCP
  selector:
    app: remedy-controller-azure
